version: '3.3'

services:
     main_app:
        build: .
        ports:
            - "8123:8123"
        depends_on:
            - database
        environment:
            - DATABASE_HOST=database
        links:
            - database:database

    database:
        build: ./Database
        ports:  
